### ISSUE TITLE
Rework Clipboard?

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#201]
Whilst testing stuff I noticed how the clipboard currently works:
Whenever a new Item is added (or deleted) the clipboard is reset.
A user might want to undo add or delete actions as well as reordering and this current limitation is intuitive imo.
To accommodate for that would a rework be feasible?
Another approach to implement a clipboard would be to hold a few copies of the current datadict. This would enable to store actions like adding, deleting, reordering and everything we already do.
In Addition to that the item menu would need a different implementation as well, maybe recreating it every reload. Since all information is stored inside the item at this point, this should be easy to implement.

**Comment by Sjoerd1993** [comment]
I agree that the current limitation is unintuitive, and being able to undo and redo actions such as removing and reordering data would be nice.I guess an option is instead of holding a copy of all x- and y data separately on each file, we can have a single datadict_clipboard variable that gets expanded with each action.It would hold a bit more data, but honestly not that much. A single data file can have thousands of data points, a could of extra attributes is not going to have a very significant impact here. We could think about wether we should limit the amount of items in the clipboard as there is always a risk of keeping too much in memory. Then on undo and redo it can just swap out the datadict to the required position, which would be a pretty similar implementation as now. The other advantage (apart from getting rid of the reset) would be that allows to undo deletion of data, which right now is irreversible. (Accidentally adding data is a minor inconvenience, accidentally removing data is not fun)The item menu doesn’t have to be changed a lot to accomodate for this I think, but at least it needs to be reloaded on undo and redo to match the datadict. It’s not really that big of a project to rework it like that. I can have a look at it tomorrow when I’m back in my computer.Skickat från min iPhone11 apr. 2023 kl. 21:31 skrev Christoph Matthias Kohnen ***@***.***>:﻿
Whilst testing stuff I noticed how the clipboard currently works:
Whenever a new Item is added (or deleted) the clipboard is reset.
A user might want to undo add or delete actions as well as reordering and this current limitation is intuitive imo.
To accommodate for that would a rework be feasible?
Another approach to implement a clipboard would be to hold a few copies of the current datadict. This would enable to store actions like adding, deleting, reordering and everything we already do.
In Addition to that the item menu would need a different implementation as well, maybe recreating it every reload. Since all information is stored inside the item at this point, this should be easy to implement.

**Comment by cmkohnen** [comment]
Regarding the datadict implementation, this would mean we'd have to change every call from datadict[key] to datadict.current_datadict[key]

Would it be possible to inherit functionality of a dict so any datadict[key] access still works?
A quick search shows it to be possible to some extend: https://realpython.com/inherit-python-dict/#inheriting-from-the-python-built-in-dict-class
An option would be to only store datadict_clipboard and the current position and on query automatically on every access. This saves at least some ram.

**Comment by cmkohnen** [comment]
I'm quickly gonna mention it here: I've written a changelist for the next release. I tried to include every change, but summed up anything not user-facing.

Graphs 1.5 Changelog

## Main Highlights
- Massive UI overhaul
- Save & Load functionality
- Customizable Plot Styles
- Loads of optimizations and refactors in the background

## Detailed changelist
- Removed PIP mode
- Removed Toolbar
- Sidebar is now responsive
- Rearranged button layouts
- Dialogs now save automatically
- Graph now has three different interaction modes: pan, zoom and select
- Operation Buttons are now enabled only when items are selected
- Operations can now be be performed for just a selected span of data
- Added combine operation
- Added custom Adwaita stylesheets for the graph
- Added a function to quickly change axis scale in the view menu
- Added a notice when no data is loaded
- Added functionality to save and load a project
- Graph ornaments like the zoom rectangle and selector overlay now follow the system colors
- Follow GNOME HIG in regards to keyboard shortcuts
- Add a warning dialog, when opening a project while data is loaded
- Separate Item related options into own dialog
- Added Toasts on some occasions
- Removed some options in Preferences, Plot Settings and the Item menu
- Added a Plot Style editor
- Plot limits can now be set in Plot Settings
- Added reordering of items via drag & drop
- Added an option to hide unselected items from the graph
- Added a dialog before exporting the figure

### background changes
- Loads of optimizations and refactors
- Blueprint is now used for the UI
- introduce linting and follow PEP8
- Many fixed bugs and edge cases

**Comment by Sjoerd1993** [comment]
You can add "Support for Panalytical .xdrml files" to the detailed changelist as well.  Other than that, most things are probably there. With an update like this we're bound to miss minor stuff, but that's fine.
