### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#485]
A few things to include before Release 1.7.0:
- Intensive testing
- A carefull rethinking of all attribute names, as changing them later on requires a bit more migration logic
- make ubuntu/snap supported(ish) by including a yaru style and setting it as default for snap
- scroll/pinch-zooming

In general we might want to release a beta and encourage people to test project migration specifically

Also depending on the GNOME Circle review process, we might want to wait a bit there.
Plus with GNOME 45 releasing relatively soon, we might want to wait and adapt to the new widgets (ToolbarView, SpinnerRow, etc.)

**Comment by Sjoerd1993** [comment]
Yeah, I too was considering waiting for GNOME 45 before releasing stable, as there are some widgets I think we should adapt. At least the AdwFlap is deprecated with the coming version, and even if it wasn't I really want to adopt the new ToolbarView, preferable as close to the GNOME 45 release as reasonable. 

There's some kinks I want to iron out anyway before releasing 1.7, and by the time we've got everything done there and did the needed testing, we will be really close to GNOME 45 anyway. 

Regarding GNOME circle, that kinda depends on the process. In principle, it would be good to avoid too many changes in the user-space in a short time. Releasing 1.7 now, and then another UI change in a few weeks depending on feedback is not ideal. So it definitely makes sense to wait a bit. But if we are in a good state after the release of GNOME 45, and are ready with the migration process to that, then I am fine releasing 1.7 at that point. But that all depends quite strongly on how long the review process takes. At the very least, we shouldn't really have open issues with regard to that to avoid changing the UI too often.

I think announcing a beta can be nice, but probably a bit closer to release when most of the planned things are implemented.

> A carefull rethinking of all attribute names, as changing them later on requires a bit more migration logic

Regarding this point, that's mostly for the attributes that are saved in the project files. Which admittingly are a lot of them, so that's still a very fair point.

> scroll/pinch-zooming

I've taken a quick look into this, so that it actually zooms into wherever the mouse is pointing. The weird thing is that the `event.xdata` and `event.ydata` that are send on a `scroll-event` are not accurate at all. But the same data that is released on a `motion_notify_event` event work perfectly fine. So a possible workaround for scroll-zooming would be to store the xdata and ydata from the `motion_notify_event` in the canvas, and use those in the scroll event. But that's really not ideal, as that rewrites attribute data on each single movement on top of the canvas. So haven't really found a super nice solution there. But there may be very other solutions that also work. By default Panning while holding right click performs the same action as scroll-to-zoom does, so I was thinking that maybe that logic could help out there. 

Pinch zooming is not something I have a lot of ideas about how to solve this.

> Intensive testing

Yeah, we'd probably be good to have a feature-freeze period before release, where we only do bugfixes and testing.

**Comment by Sjoerd1993** [comment]
Actually, now I think of it, publicly announcing a beta soon-ish can make sense. 

It would leave for the possibility of getting some feedback a bit earlier, and gives a chance to plug the Weblate localization, giving the possibility for contributions there before actual release. 

The question then when to do that. We can make it part of the next This Week in GNOME, which has their deadline tomorrow (always on Friday's), or we can wait a while until recent additions are slightly more polished.

**Comment by cmkohnen** [comment]
Well to give an idea timewise, my semester starts this mondey and I do not know how this will affect my ability to contribute here. For an announcment in e. g. GNOME Circle, there should be an issue with somewhat detailed steps for testing purposes.

**Comment by Sjoerd1993** [comment]
Yeah no worries, I've always thought of our release schedule as an "it's finished when it's finished" kind of thing. Free time will always come and go, so if development is slower due to other things happening in real life, then the release will simply be a bit later. It's all basically volunteer work after all. 

I also just realized GNOME 45 releases next week already, I was actually thinking about October when writing yesterday, which is when Fedora 39 releases. Again, we need to do thorough testing before releasing 1.7.0. So releasing within a week or two from now is not the timeline I was thinking of, perhaps a beta within that timeline but not an official release yet.

 I will also release some unit tests for the migration and Project imports soon, so that backwards compatibility checks are automated.

**Comment by Sjoerd1993** [comment]
I wrote a general list of things that need to be done as a milestone for the 1.7 release. Feel free to add those, or keep a list in the issue seperately:


Planned changes to the code-base:
- [ ] Add pre-defined equations for the curve fitting tool
- [ ] Add statistics to the curve fitting tool
- [ ] Add the option to show a confidence band to the curve fitting tool
- [ ] Scroll- and pinch to zoom gestures in Matplotlib
- [ ] A careful rethinking of all attribute names, as changing them later on requires a bit more migration logic
- [ ] Make Ubuntu/snap supported(ish) by including a yaru style and setting it as default for snap
- [ ] Update to GNOME 45

Open blocker bugs to be fixed for 1.7.0:
- [ ] The radian scaling crashes for large data sets.
- [ ] The decimal separator option does not show in the import menu before opening the dropdown.

Waiting for:
- [ ] Any open feedback from the GNOME Circle review process should be implemented when releasing.

Release steps:
- [ ] Create new screenshots 
- [ ] Write general changelist
- [ ] Start beta feedback period
- [ ] Update appdata before final release
- [ ] Testing period (probably add least a week) where we only do testing and bug fixes
- [ ] Bump version number
- [ ] Tag release on Github, and push release to Flathub and Snap

**Comment by cmkohnen** [comment]
Regarding the next release we might want to make a string-freeze soonish, so that translations can be given time before the release comes out. Atm, this is tied to whether or not existing strings in the UI are acceptible and HIG compliant

**Comment by Sjoerd1993** [comment]
> Regarding the next release we might want to make a string-freeze soonish, so that translations can be given time before the release comes out. Atm, this is tied to whether or not existing strings in the UI are acceptible and HIG compliant

Yes, I think that would be good. Which would require us also to take a quick last crititical look at the strings before the freeze. Also some strings will be added when #494 is implemented. Hopefully I can take a look at that soon. Otherwise, I probably won't add any UI-changing features before release. This would also mean #625 will remain open then for now.

Either way, a string freeze is probably a good idea. Maybe deserves a seperate issue even.

**Comment by Sjoerd1993** [comment]
Once the current PR's are merged, most outstanding issues are basically closed and I think we could announce a beta on the TWIG blog. Then somewhere early in the new year we should be able to make an official release. Only thing I've got left on my list is to see if I can figure out how to git rid of the pencil icons in the AdwEntry rows as @bertob suggested in the GNOME Circle Review. Been told it should be possible with CSS but haven't been successful with it so far.

I think #625 could then be implemented for the release after with a general redesign of the import file dialog. That dialog is fine, but I think there's room for design improvements there.
