### ISSUE TITLE
Rethinking Style Management

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#529]
In order to adress feedback from the GNOME Circle application, I've made a mockup of how we could expose Styles to the user (It's on paper as I haven't got the time to learn tools on creating one digitally).
![IMG_20231002_072102](https://github.com/Sjoerd1993/Graphs/assets/59118042/b0ee60d6-be2a-4608-aef3-220a2f96c271)

The Idea is to have this as a subsection of the Figure Settings. For the selection I have one slight alternative in mind: Instead of choosing between System and Custom just present one style on top named "System".

The Previews can be generated via rendering a figure to an image and embedding said image. For system styles, we can even bundle these images to save compute resources. For user styles these have to be generated on runtime however.

**Comment by cmkohnen** [comment]
Oh, Feedback and criticism highly apprechiated

**Comment by Sjoerd1993** [comment]
Looking at this quickly, this looks incredibly good. One slight pain point in the current design, is that I am often a bit inclined to go to styles when I want to set a new style. So it feels there's some friction there currently, and I'm all for integrating this with the figure settings. We can probably use the NavigationView widget for the Figure Settings dialog then, the same one that we use for the Styles dialog now. This inclination that I had is also why I proposed the "set as current style" button in the style sheet editor, but that was indeed a bit of an inconsistent design which is why we abandoned that.

Either way to the main thing of this mock up in general. I think this looks absolutely fantastic. It will look visually pleasing, but at the same time allows the user to immediately see what each style looks like and set the style of choice. I'll share what I was thinking of earlier, as I was considering a redesign of this before the feedback, but I'm this mockup has my very strong preference. Really good ideas in here.

One thing I'm unsure of is if we'd want to make a visual distinction between the custom styles and the shipped styles (seaborn and such), or if we'd present them in the same list with the only difference being an edit pencil and the trash icon. Honestly not sure what would work best. But at the very least in the first implementation I think it would work fine if we'd keep these in the same list.

We also need to think about the technical implementation of the preview images. Of course pre-set images for each style would be relatively easy, and won't require too much resources. But then we'd have to think about how to do this with the custom ones. One option is to simply ship a "custom placeholder" image for the custom styles. But it'd be prettiest to generate this with matplotlib, I'm just not sure if it's technically nice to generate a whole bunch of canvases at runtime, including at least two lines each. (Perhaps it's fine). Perhaps it's possible to generate an image when a style is edited, and use that. Either way, it's a technical problem that's definitely solvable.

Also we'd need to think if we'd scale the fonts then for instance to real size, as that can make the preview quite ugly for bigger font sizes that work fine in the big screen but not in the preview. (We can probably just cap the font size though).

**Comment by Sjoerd1993** [comment]
Also pinging @bertob here, just to keep him in the loop on the ideas here. As this is probably the biggest change/redesign that will follow from this round of feedback at least.

On a different note, it may be somewhat obvious but this new style editor should probably be considered a blocker for releasing v1.7. Along with the other GNOME Circle feedback. As I'd prefer to keep the bigger changes to the UI mostly confined to this release instead of shipping yet another big overhaul a month later.

Which will probably make v1.7 our biggest update yet. It's been a while since the latest version, but in this case it makes sense to wait.

**Comment by cmkohnen** [comment]
![IMG_20231002_101959.jpg](https://github.com/Sjoerd1993/Graphs/assets/59118042/5b9d6426-14f3-4ec1-823f-66aeb19ede9a)

Another design for showing the styles, which I like a bit more

**Comment by cmkohnen** [comment]
![IMG_20231002_102148.jpg](https://github.com/Sjoerd1993/Graphs/assets/59118042/8024d568-8a1d-4a93-9746-bcdf62909325)

A slihhtly improved way of liating styles

**Comment by Sjoerd1993** [comment]
Biggest difference would primarily be that instead of setting the system theme distinctly on top, that it is placed with the other themes albeit at the first position. Which works fine as well. I do like the "Add" button being in the header bar, that will probably look a lot cleaner. So that is likely cleaner in the end.

Having these presented like this in the same list, there is a change that we may replicate some styles. E.g. having "System, Adwaita" as the first two options will give two identical styles in light mode. That is somewhat less awkward when the system style is shown separately. Of course, a major difference is that the system style also adapts to dark/light mode. So we want both options available either way (one should be able to set adwaita-dark in light mode and vice versa). So maybe that's not a giant issue. 

An alternative is also to keep using a "Use system style" toggle, as we have now. But instead of the dropdown in figure setting, clicking the custom styles leads us to the mockup in the above picture. This way we won't have to present the system style in the list of style sheets as a separate entity. Not 100% sure though. As I do think it may feel a bit more streamlined to have the system style somewhat integrated with the other styles as the mockups in this thread.

**Comment by cmkohnen** [comment]
I feel like including it inside the main list would be the most coherent. To distinguish a little better, we can use a split to indicate that system supports both dark and light.

Also when editing styles, there is a discussion to be had, whether to edit in the same window or open a popup. In this case I'd prefer a popup editor to better clarify that editing is a little different than just selecting a style.

**Comment by Sjoerd1993** [comment]
Using a split for the system theme has crossed my mind as well, but back then I was thinking of it functioning primarily as a way to show that this adapts to dark/light mode. But it indeed also clearly distinguishes the system theme from the other themes. So I think that would be a pretty nice solution actually that would keep everything quite clean. 

If we ever were to implement an option to set a dark/light variant for custom themes, we can think if we'd need some more distinction or not. But that's not a thing that I think we should implement in the short term at least. If it's even a thing that we'd want to add at all.

Regarding the question of the same window or a pop-up. It would mean that there'd be another modal window on top of the current modal window. It's not a hard rule that it should never ever happen, but in principle the GNOME HIG state we should [avoid stacking secondary windows](https://developer.gnome.org/hig/patterns/containers/windows.html) on top of each other. I think it would in principle work quite well with just another page of AdwNavigationView.

However, I don't mind experimenting with a pop-up window in the first implementation of this at least. We probably need to iterate a bit either way and changing from a pop-up to an AdwNavigationPage is relatively easy.
