### ISSUE TITLE
Legend position menu capitalization

### ISSUE THREAD

**Issue by bertob** [Sjoerd1993/Graphs#717]
The menu items in the legend position menu are not title case:

![image](https://github.com/Sjoerd1993/Graphs/assets/1908896/2a8866eb-ebe7-45af-84d4-7bb5f75fe89e)

**Comment by Sjoerd1993** [comment]
Woops, thanks for noticing. Have put a PR that fixes this. Can probably push this out in a quick patch so that it's fixed before the next TWIG issue. 

I always notice that this brings a measurable amount of installs, so would be nice to have that updated then (I also see in the Github analytics that most unique visitors come from either TWIG or Planet GNOME).
