### ISSUE TITLE
Selection persists after viewport changes

### ISSUE THREAD

**Issue by bertob** [Sjoerd1993/Graphs#719]
When selecting part of a function and applying a derivative, the rest of the function is cut off and the view changes to just the selection. However, the old selection is still visible, except it's now a much smaller range. This is confusing because it makes it seem like the visible range didn't actually change.

I'd either hide the selection or make it actually reflect the same range as before the operation.

[Screencast from 2024-01-11 13-39-37.webm](https://github.com/Sjoerd1993/Graphs/assets/1908896/8d760f9e-e728-43e9-b5c8-8bd09fefa1f9)

**Comment by Sjoerd1993** [comment]
I was aware of this issue, and it was on my list. The issue is that the way that the highlight works is that it has to be connected to one pair of axes. In total we've got four pair of axes that are kinda kept in sync:

Bottom-left
Bottom-right
Top-left
top-right

This is simply due to how matplotlib works, having the system with multiple axes is not really a thing we can get around. So the highlight is attached to the top-right axis, and it calculates what data falls into the span using it's "fractional position". Here it also converts coordinate system, as the bottom axes may be on a log-scale for example.

Anyway, without getting too much into details. The highlight is defined by where it is on the screen so to speak, and not to the exact coordinates. Hence it staying on the same place after the operation, despite the fact that the underlaying numbers in that area has changed.

I think hiding the highlight after operation is a sensible workaround for now. Especially given that you typically don't want to perform an operation twice on the exact same area anyway. Which is what PR #720 does.

**Comment by Sjoerd1993** [comment]
Demonstration for clarity:

[Skärminspelning från 2024-01-11 14-23-19.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/3ae51955-db5f-49e3-abfd-d66b8c9b7b18)
